### ISSUE TITLE
Directions of Menu bar sign

### ISSUE THREAD

**Issue by ghost** [collecteddoc/O-M#34]
Menu bar Signs should be in opposite direction, As like in Expanding order. 
![Menu bar icon direction](https://user-images.githubusercontent.com/54391338/64105087-5917d280-cd97-11e9-9842-594212ddd0b4.png)

**Comment by teksoi** [comment]
fixed

**Comment by ghost** [comment]
Not fixed. Still now the same.

**Comment by ghost** [comment]
Not fixed. Arrow signs are still now same.

![arrow sign](https://user-images.githubusercontent.com/54391338/66713800-1eab4780-edd1-11e9-9e46-dda92603840c.png)

**Comment by teksoi** [comment]
This is universal behavior of the opensource project on which this project depends
 
![issue_34](https://user-images.githubusercontent.com/53424504/69010764-14123e00-098d-11ea-9381-5e0389fe1344.png)
