### ISSUE TITLE
Vacant Form Input Giving Error.

### ISSUE THREAD

**Issue by ghost** [collecteddoc/O-M#45]
Path: **Reservation Time for Position** 
**Issue:** Whatever date is being inserted into the Vacant Form ; it is giving error while saving. Not showing the Reason. 
![2019-09-03_13-40-31](https://user-images.githubusercontent.com/54391338/64159570-474c3300-ce5c-11e9-801e-71e9dfed775c.png)

**Comment by teksoi** [comment]
fixed

**Comment by ghost** [comment]
Not solved, Giving error.
Check the Image.
**Giving error whenever clicked on the save button now.**
**Previously selected data's are staying selected**
**No Mandatory signs are given**
**Alignment is not correct of the calendar icon**
![post reservatons](https://user-images.githubusercontent.com/54391338/64920879-2c73aa00-d7de-11e9-8b0a-91b6ffd04e7e.png)
